export const CREATE_COURSE = "CREATE_COURSE";
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCES";
export const LOAD_AUTHORS_SUCEES = "LOAD_AUTHORS_SUCCES";
export const CREATE_COURSE_SUCCEES = "CREATE_COURSE_SUCCEES";
export const UPDATE_COURSE_SUCCEES = "UPDATE_COURSE_SUCCEES";
